owner: StefCoders
repo: status

sites:
  - name: StefCodes
    url: https://stefcodes.co.uk
  - name: DeepRadio
    url: https://deepradio.co.uk
  - name: MoinestiFM
    url: https://moinestifm.ro
  - name: DeepRadio Listen
    url: https://listen.deepradio.co.uk
    port: 80
    check: "tcp-ping"
  - name: MoinestiFM Listen
    url: https://listen.moinestifm.ro

status-website:
  cname: status.stefcodes.co.uk
  logoUrl: https://deepradio.co.uk/images/logo.jpg
  name: Upptime
  introTitle: "**StefCodes's Services**"
  introMessage: This is a status page to show all of my services and their status, powered by Github.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: StefCodes
      href: https://stefcodes.co.uk
    - title: DeepRadio
      href: https://deepradio.co.uk
    - title: MoinestiFM
      href: https://moinestifm.ro
